[deps]
Boltz = "4544d5e4-abc5-4dea-817f-29e4c205d9c8"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
Metalhead = "dbeba491-748d-5e0e-a39e-b530a07fa0cc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[sources]
Boltz = {path = "../.."}

[compat]
Boltz = "1"
JLD2 = "0.5, 0.6"
Lux = "1.21.2"
Metalhead = "0.9.3"
Random = "1.10"
